function ensureAddons(p){if(!p.addons)p.addons={coat:false,ear:false,pluck:false,mala:'',deg:'',nail:false,gland:false,sani:false,teeth:false};if(p.type!=='cat')p.addons.deg='';if(p.type!=='dog')p.addons.pluck=false;return p.addons}
function addonCopy(){const t=T();const base={coat:'ทรีตเมนต์บำรุงเส้นขน',coatEn:'Coat Conditioning Treatment',coatD:'ช่วยบำรุงเส้นขนให้นุ่มลื่น หวีจัดทรงง่าย ลดความพันกัน และเพิ่มสัมผัสที่นุ่มนวนให้ขนดูสวยสุขภาพดี',ear:'บริการล้างหูด้วยน้ำยาทำความสะอาดหู',earEn:'Deep Ear Cleansing',earD:'เพิ่มการดูแลช่องหูด้วยน้ำยาล้างหูสำหรับสัตว์เลี้ยง เพื่อช่วยชะล้างคราบขี้หูและสิ่งสกปรกที่สะสมตามความเหมาะสม นอกเหนือจากการเช็ดหูตามปกติ',pluck:'ถอนขนหู',pluckEn:'Ear Hair Plucking',pluckD:'ถอนขนในรูหูสำหรับสุนัข ช่วยระบายอากาศและทำความสะอาดรูหูได้ดีขึ้น (เฉพาะสุนัข)',mala:'บริการอาบแชมพูยา Malaseb',malaEn:'Malaseb Medicated Bath',malaD:'แชมพูสูตรยาที่มีส่วนผสมของ miconazole และ chlorhexidine ใช้ช่วยจัดการปัญหาผิวหนังที่เกี่ยวข้องกับเชื้อยีสต์และแบคทีเรียบางชนิดในสุนัขและแมวตามข้อบ่งใช้ของผลิตภัณฑ์ เหมาะสำหรับการดูแลผิวหนังตามคำแนะนำของสัตวแพทย์',deg:'บริการขจัดคราบมันสะสมบนเส้นขน',degEn:'Deep Degreasing Treatment',degD:'ช่วยทำความสะอาดความมันส่วนเกินและคราบมันที่เกาะบนเส้นขน ทำให้ขนรู้สึกสะอาด เบาสบาย และจัดทรงง่ายขึ้น เหมาะสำหรับสัตว์เลี้ยงที่มีขนมันเป็นพิเศษ',nail:'บริการตะไบเก็บขอบเล็บ',nailEn:'Nail Finishing',nailD:'ช่วยเก็บขอบเล็บให้เรียบมน ลดความคมหลังตัดเล็บ และช่วยให้การสัมผัสหรืออุ้งเท้าสัมผัสผิวหนังเป็นไปอย่างนุ่มนวลยิ่งขึ้น',gland:'บีบต่อมเหม็น',glandEn:'Anal Gland Expression',glandD:'ช่วยระบายของเหลวที่สะสมในต่อมข้างก้น ลดกลิ่นไม่พึงประสงค์และอาการไถก้นกับพื้น',sani:'ไถขนก้น',saniEn:'Sanitary Trim',saniD:'ไถขนรอบก้นให้สั้นเรียบร้อย ช่วยให้สะอาดและลดคราบติดขน',teeth:'แปรงฟัน',teethEn:'Tooth Brushing',teethD:'แปรงฟันด้วยแปรงและยาสีฟันสำหรับสัตว์เลี้ยง ช่วยลดคราบบนฟันและกลิ่นปาก'};if(lang==='th'||!t.ad)return base;return Object.assign(base,t.ad)}
function row(key,price,p,i){const L=addonCopy(),a=ensureAddons(p);return '<label class="check"><input type="checkbox" data-add="'+key+'" data-i="'+i+'" '+(a[key]?'checked':'')+' style="width:auto"/> <b>'+L[key]+'</b> '+(price?'+'+price:(T().free||'ฟรี'))+'</label><p class="hint">'+L[key+'En']+'</p><p class="hint">'+L[key+'D']+'</p>'}
function choice(key,spot,full,p,i){const t=T(),L=addonCopy(),a=ensureAddons(p);return '<p><b>'+L[key]+'</b></p><p class="hint">'+L[key+'En']+'</p><p class="hint">'+L[key+'D']+'</p><label class="check"><input type="radio" name="'+key+i+'" data-add="'+key+'" data-val="spot" data-i="'+i+'" '+(a[key]==='spot'?'checked':'')+' style="width:auto"/> '+(t.spot||'1 จุด')+' +'+spot+'</label><label class="check"><input type="radio" name="'+key+i+'" data-add="'+key+'" data-val="full" data-i="'+i+'" '+(a[key]==='full'?'checked':'')+' style="width:auto"/> '+(t.full||'ทั้งตัว')+' +'+full+'</label>'}
function addonHtml(p,i){const t=T();return '<div class="card" data-addon-box="'+i+'"><strong>'+(t.addons||'บริการเสริม')+'</strong><p class="hint">'+(t.addonLead||'เลือกได้มากกว่า 1 อย่าง ไม่รวมในมัดจำ')+'</p>'+row('coat',50,p,i)+row('ear',50,p,i)+(p.type==='dog'?row('pluck',50,p,i):'')+choice('mala',50,100,p,i)+(p.type==='cat'?choice('deg',100,500,p,i):'')+row('nail',50,p,i)+row('gland',30,p,i)+row('sani',0,p,i)+row('teeth',50,p,i)+'<label>'+(t.reqLabel||'อยากให้เสริมอะไรเพิ่มเติมไหมคะ (ไม่บังคับ)')+'</label><textarea data-req="'+i+'" maxlength="300" placeholder="'+(t.reqPh||'เช่น เช็ดคราบน้ำตา, ทำโบว์')+'">'+escAdd(p.req||'')+'</textarea><p class="hint" data-addsum="'+i+'">'+addonSumText(p)+'</p></div>'}
function escAdd(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function addonPrice(p){const a=ensureAddons(p);let s=0;if(a.coat)s+=50;if(a.ear)s+=50;if(p.type==='dog'&&a.pluck)s+=50;if(a.mala==='spot')s+=50;else if(a.mala==='full')s+=100;if(p.type==='cat'){if(a.deg==='spot')s+=100;else if(a.deg==='full')s+=500}if(a.nail)s+=50;if(a.gland)s+=30;if(a.teeth)s+=50;return s}
function addonSumText(p){const t=T();return (t.addSum||'รวมบริการเสริม')+' ฿'+addonPrice(p)+' · '+(t.addPay||'ชำระที่ร้าน ไม่รวมในมัดจำ')}
function addonText(p){const L=addonCopy(),a=ensureAddons(p),t=T(),out=[];if(a.coat)out.push(L.coat);if(a.ear)out.push(L.ear);if(p.type==='dog'&&a.pluck)out.push(L.pluck);if(a.mala)out.push(L.mala+' '+(a.mala==='full'?(t.full||'ทั้งตัว'):(t.spot||'1 จุด')));if(p.type==='cat'&&a.deg)out.push(L.deg+' '+(a.deg==='full'?(t.full||'ทั้งตัว'):(t.spot||'1 จุด')));if(a.nail)out.push(L.nail);if(a.gland)out.push(L.gland);if(a.sani)out.push(L.sani+' ('+(t.free||'ฟรี')+')');if(a.teeth)out.push(L.teeth);return out.join(', ')}
function paintAddons(){if(typeof step==='undefined'||step!==1)return;document.querySelectorAll('#s1 [data-addon-box]').forEach(el=>el.remove());document.querySelectorAll('#s1 select[data-k="svc"]').forEach(sel=>{sel.insertAdjacentHTML('afterend',addonHtml(pets[+sel.dataset.i],+sel.dataset.i))});document.querySelectorAll('[data-add]').forEach(el=>el.onchange=()=>{const p=pets[+el.dataset.i];ensureAddons(p);if(el.type==='checkbox')p.addons[el.dataset.add]=el.checked;else p.addons[el.dataset.add]=el.dataset.val;const sum=document.querySelector('[data-addsum="'+el.dataset.i+'"]');if(sum)sum.textContent=addonSumText(p)});document.querySelectorAll('[data-req]').forEach(el=>el.oninput=()=>{pets[+el.dataset.req].req=el.value.slice(0,300)});document.querySelectorAll('#s1 select[data-k="type"]').forEach(el=>{el.addEventListener('change',()=>{pets[+el.dataset.i].type=el.value;ensureAddons(pets[+el.dataset.i]);render()})})}
const _renderAdd=render;render=function(){_renderAdd();paintAddons();if(step===2){document.querySelectorAll('#s2 .card p').forEach((el,i)=>{if(pets[i]&&addonText(pets[i])&&el.querySelector('b'))el.insertAdjacentHTML('beforeend','<br>'+addonText(pets[i]));if(pets[i]&&pets[i].req&&el.querySelector('b'))el.insertAdjacentHTML('beforeend','<br>'+(T().reqShort||'คำขอเพิ่มเติม')+': '+escAdd(pets[i].req))})}}
