I.en={steps:['Your pet','Your details','Date and time','Confirm'],h1:'Book a visit',lead:'Tell us about them so we can prepare the right care.',pet:'Pet',name:'Name',type:'Type',svc:'Service',note:'Anything we should know?',nph:'Tell the groomer...',hint:'For example: afraid of water, dislikes the dryer, sensitive paws.',none:'Nothing to note',add:'+ Add another pet',pt:'Before we take them in',p:'For safety, we cannot accept pets who bite, scratch, or are too fearful for the service.',p2:'Not sure? Message us on LINE first.',hours:'Time needed',dep:'Deposit',next:'Continue',h2:'A little about you',l2:'So we can reach you about the visit.',owner:'Your name',phone:'Phone',back:'Back',toTime:'Choose a time',h3:'A time that suits them',l3:'Pick a date and time. We will keep that window for them.',date:'Date',times:'Open times',closed:'Closed this day.',busy:'Already booked',toPay:'Review',h4:'Review your booking',pay:'Pay deposit',ok:'All set',okL:'We have the request. Send the slip on LINE and we will confirm the queue.',line:'Send the slip on LINE',dog:'Dog',cat:'Cat',rabbit:'Rabbit',sv:{addon:'Add-on only',bath:'Bath',cut:'Trim only',clip:'Bath + clipper',scissor:'Bath + scissor'}};
I.zh={steps:['毛孩子','您的资料','日期时间','确认预约'],h1:'为毛孩子预约',lead:'告诉我们它的习惯，我们会按它来准备。',pet:'第',name:'名字',type:'种类',svc:'服务',note:'有什么我们应该知道的吗？',nph:'直接告诉美容师就好',hint:'例如怕水、怕吹风、不喜欢被碰脚。',none:'没有需要注意的',add:'+ 再加一只',pt:'接待前',p:'若有咬、抓，或害怕到无法服务，本店恕不接待。',p2:'不确定就先在 LINE 询问。',hours:'大约时间',dep:'订金',next:'继续',h2:'先认识你一下',l2:'方便我们联系你。',owner:'主人姓名',phone:'电话',back:'返回',toTime:'选择时间',h3:'选一个适合它的时间',l3:'选好日期和时间，这段时间会留给它。',date:'日期',times:'可预约时间',closed:'这天店休。',busy:'已有预约',toPay:'核对预约',h4:'核对你的预约',pay:'支付订金',ok:'好了',okL:'已收到预约。把截图发到 LINE，美容师会确认。',line:'把截图发到 LINE',dog:'狗',cat:'猫',rabbit:'兔子',sv:{addon:'附加服务',bath:'洗澡',cut:'只剪毛',clip:'洗澡 + 剑毛',scissor:'洗澡 + 剪刀'}};
I.th.addons='บริการเสริม';I.th.addonLead='เลือกได้มากกว่า 1 อย่าง ไม่รวมในมัดจำ';I.th.spot='1 จุด';I.th.full='ทั้งตัว';
I.en.addons='Add-ons';I.en.addonLead='Choose any. These are extra and not included in the deposit.';I.en.spot='One spot';I.en.full='Full body';
I.en.ad={coat:'Coat conditioning treatment',coatEn:'Coat Conditioning Treatment',coatD:'Conditions the coat so it feels softer, combs out more easily, tangles less, and has a gentler feel.',ear:'Deep ear cleansing',earEn:'Deep Ear Cleansing',earD:'Extra ear care with a pet ear cleanser, to rinse built-up wax and dirt beyond a normal wipe.',pluck:'Ear hair plucking (dogs)',pluckEn:'Ear Hair Plucking',pluckD:'Plucks hair inside the ear canal for dogs, to help the ear stay clearer and easier to clean. Dogs only.',mala:'Malaseb medicated bath',malaEn:'Malaseb Medicated Bath',malaD:'A medicated shampoo with miconazole and chlorhexidine, used for skin issues linked to certain yeast and bacteria in dogs and cats, as directed on the product. Suitable for skin care advised by a veterinarian.',deg:'Deep degreasing treatment',degEn:'Deep Degreasing Treatment',degD:'Cleans excess oil and greasy buildup on the coat, so it feels cleaner, lighter, and easier to finish. For pets with an especially oily coat.',nail:'Nail finishing',nailEn:'Nail Finishing',nailD:'Smooths the nail edges after trimming, so they are less sharp and gentler when paws touch skin.'};
I.zh.addons='附加服务';I.zh.addonLead='可多选。这些是加项，不含在订金内。';I.zh.spot='一个部位';I.zh.full='全身';
I.zh.ad={coat:'毛发护理',coatEn:'Coat Conditioning Treatment',coatD:'让毛发更柔顺、更好梳，减少打结，触感更好。',ear:'深层洗耳',earEn:'Deep Ear Cleansing',earD:'用宠物洗耳液额外护理耳道，冲洗积聚的耳垢和污垢，不只是普通擦耳。',pluck:'拔耳毛（仅狗狗）',pluckEn:'Ear Hair Plucking',pluckD:'为狗狗拔除耳道内的毛，帮助耳道更通风、更好清洁。仅限狗狗。',mala:'Malaseb 药浴',malaEn:'Malaseb Medicated Bath',malaD:'含 miconazole 和 chlorhexidine 的药用香波，按产品说明使用，用于狗猫皮肤上与某些真菌、细菌相关的问题，适合按兽医建议护理皮肤。',deg:'深层去油',degEn:'Deep Degreasing Treatment',degD:'清除毛发上过多的油脂和油垢，让毛发更干净、更轻，也更好整形。适合油毛明显的宠物。',nail:'修磨甲缘',nailEn:'Nail Finishing',nailD:'把剪完的甲缘磨圆，减少刮感，蹭脚接触皮肤时更柔和。'};

I.th.myPets='น้องของคุณ';I.th.myPetsHint='แตะชื่อน้องเพื่อเลือก ไม่ต้องกรอกใหม่';I.th.welcome='ยินดีต้อนรับกลับค่ะ คุณ';I.th.max2='จองได้ครั้งละไม่เกิน 2 ตัว';
I.en.myPets='Your pets';I.en.myPetsHint='Tap a name to add them. No retyping needed.';I.en.welcome='Welcome back, ';I.en.max2='Up to 2 pets per booking.';
I.zh.myPets='你的毛孩子';I.zh.myPetsHint='点名字即可选择，无需重新填写。';I.zh.welcome='欢迎回来，';I.zh.max2='每次最多预约 2 只。';
I.th.free='ฟรี';I.th.reqLabel='อยากให้เสริมอะไรเพิ่มเติมไหมคะ (ไม่บังคับ)';I.th.reqPh='เช่น เช็ดคราบน้ำตา, ทำโบว์';I.th.reqShort='คำขอเพิ่มเติม';I.th.addSum='รวมบริการเสริม';I.th.addPay='ชำระที่ร้าน ไม่รวมในมัดจำ';
I.en.free='Free';I.en.reqLabel='Anything else you would like us to add? (optional)';I.en.reqPh='e.g. tear stain cleaning, a bow';I.en.reqShort='Extra request';I.en.addSum='Add-ons total';I.en.addPay='paid at the shop, not part of the deposit';
I.zh.free='免费';I.zh.reqLabel='还想加点什么吗？（选填）';I.zh.reqPh='例如：清理泪痕、戴蝴蝶结';I.zh.reqShort='额外需求';I.zh.addSum='附加服务合计';I.zh.addPay='到店支付，不含在订金内';
Object.assign(I.en.ad,{gland:'Anal gland expression',glandEn:'Anal Gland Expression',glandD:'Gently empties the glands beside the bottom to reduce odour and scooting.',sani:'Sanitary trim',saniEn:'Sanitary Trim',saniD:'A short, neat trim around the bottom to keep it clean.',teeth:'Tooth brushing',teethEn:'Tooth Brushing',teethD:'Brushing with a pet toothbrush and toothpaste to help reduce plaque and bad breath.'});
Object.assign(I.zh.ad,{gland:'挤肛门腺',glandEn:'Anal Gland Expression',glandD:'帮助排出肛门两侧腺体的积液，减少异味和蹭屁股。',sani:'屁屁周围剃毛',saniEn:'Sanitary Trim',saniD:'把屁屁周围的毛剃短剃整齐，更干净卫生。',teeth:'刷牙',teethEn:'Tooth Brushing',teethD:'用宠物牙刷和牙膏刷牙，帮助减少牙垢和口臭。'});
